# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: ADOScheduledWorkItemQuery@0
  inputs:
    sendMethod: 'SendGrid'
    connectedServiceNameSendGrid: 'Azure devops'
    project: '9269bacf-bdd7-4ca2-9c23-eb06f205ff53'
    queryType: 'Shared'
    query: '677a4766-2bd1-4cbc-bd37-18c36f389cbd'
    sendIfEmpty: true
    subject: 'Your query results'
    emailAddresses: 'urszulasype@gmail.com'
  
