apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-mongodb
spec:
  # backup the database every day at 22
  schedule: "0 22  * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
              - name: regcred
          containers:
          - name: backup-mongodb
            image: pmdev01.azurecr.io/backup-mongo:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                  name: backup-mongo
          restartPolicy: Never
status: {}  