apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-dump
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile
